language: node_js
node_js:
  - "11.12"
  - "11.10"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gulp
# Build docs, test build
script:
  - gulp build
install:
  - npm install
