language: node_js
node_js:
  - "6.2"
  - "6.1"
  - "6"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g gulp
  - gem install jekyll
# Build docs, test build
script:
- gulp build
install:
  - npm install
